#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

type GenAIEvaluationRecords {
    genAIEvaluationRecordList: [GenAIEvaluationRecord!]!
    errorReason: String
    debuggingTrace: DebuggingTrace
}

type GenAIEvaluationRecord {
    traceId: String
    serviceId: String
    serviceInstanceId: String
    segmentId: String
    spanId: String
    spanType: String
    taskName: String
    valueType: String
    value: String
    evaluationLevel: String
    reason: String
    judgeModel: String
    evaluationTime: Long
}

input GenAIEvaluationRecordTag {
    key: String!
    value: String
}

input GenAIEvaluationRecordQueryCondition {
    serviceId: ID
    serviceInstanceId: ID
    relatedTrace: TraceScopeCondition
    queryDuration: Duration
    paging: Pagination!
    tags: [GenAIEvaluationRecordTag!]
    queryOrder: Order
}

extend type Query {
    supportGenAIEvaluationRecordQueryByKeywords: Boolean!
    queryGenAIEvaluationRecord(condition: GenAIEvaluationRecordQueryCondition, debug: Boolean): GenAIEvaluationRecords
}